<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Mysql on 程序猿的小本本</title>
    <link>/tags/mysql/</link>
    <description>Recent content in Mysql on 程序猿的小本本</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <managingEditor>chennqqi@qq.com (chennqqi)</managingEditor>
    <webMaster>chennqqi@qq.com (chennqqi)</webMaster>
    <copyright>(c) 2016 gsymy.com.</copyright>
    <lastBuildDate>Thu, 01 Dec 2016 21:20:40 +0800</lastBuildDate>
    
	<atom:link href="/tags/mysql/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>python mysql 2014 error</title>
      <link>/2016/12/02/python-mysql-2014-error.html</link>
      <pubDate>Thu, 01 Dec 2016 21:20:40 +0800</pubDate>
      <author>chennqqi@qq.com (chennqqi)</author>
      <guid>/2016/12/02/python-mysql-2014-error.html</guid>
      <description>###python mysqlDB批量插入数据时报错
python MySQLdb module error code:
Error 2014: Commands out of sync; you can&#39;t run this command now
This happened when excute mysql batch operation. Solution:
Every mysql option done, then call commit()
Using executemany funcion is recommand.
list = [] sql = &#39;INSERT INTO tablexxx(a,b,c) VALUES(%s,%s,%s)&#39; for l in ll: list.append(l) db.executemany(sql, list)#db.fetchmany() ... db.commit()  </description>
    </item>
    
  </channel>
</rss>